config/routes.rb
Rails.application.routes.draw do
  resources :sheets do
    resources :columns
  end
end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
  attr_accessor :column_count, :row_count, :no_logging

  has_many :columns, dependent: :destroy
  has_many :rows, dependent: :destroy

  after_save :create_columns, :create_rows

  def data
    rows.map(&:to_a).to_json
  end

  def no_logging
    @no_logging ||= false
  end

  def column_count
    @column_count ||= 2
  end

  def row_count
    @row_count ||= 2
  end

  # Add pos[:count] columns at position pos[:at]
  def add_column(pos)
    start = pos[:at].to_i
    count = pos[:count].to_i
    columns.each do |column|
      column.position += count if column.position >= start
    end
    count.times { columns.new(position: pos[:at]) }
    saved = columns.collect {|column| column.save }
    saved.all?
  end

  # Add pos[:count] rows at position pos[:at]
  def add_row(pos)
    start = pos[:at].to_i
    count = pos[:count].to_i
    rows.each do |row|
      row.position += count if row.position >= start
    end
    count.times { rows.new(position: pos[:at]) }
    saved = rows.collect {|row| row.save }
    saved.all?
  end

  # Move a column from pos[:from] to post[:dest]
  def move_column(pos)
    from = pos[:from].to_i
    dest = pos[:dest].to_i

    # Moving right
    if dest > from
      rws = columns.where(position: from..dest)
      rws.each do |col|
        if col.position == from
          moving = col
          moving.position = -1
        else
          col.position -= 1
        end
      end
      moving.position = dest

    # Moving left
    else
      rws = columns.where(position: dest..from)
      rws.each do |col|
        if col.position == from
          moving = col
          moving.position = -1
        else
          col.position += 1
        end
      end
      moving.position = dest
    end

    saved = rws.map(&:save)
    saved.all?
  end

  # Move a row from pos[:from] to post[:dest]
  def move_row(pos)
    from = pos[:from].to_i
    dest = pos[:dest].to_i
    moving = nil

    # Moving down
    if dest > from
      rws = rows.where(position: from..dest)
      rws.each do |row|
        if row.position == from
          moving = row
          moving.position = -1
        else
          row.position -= 1
        end
      end
      moving.position = dest

    # Moving up
    else
      rws = rows.where(position: dest..from)
      rws.each do |row|
        if row.position == from
          moving = row
          moving.position = -1
        else
          row.position += 1
        end
      end
      moving.position = dest
    end

    saved = rws.map(&:save)
    saved.all?
  end

  # Remove pos[:count] columns at position pos[:at]
  def drop_column(pos)
    start = pos[:at].to_i
    count = pos[:count].to_i
    stop  = start + count - 1
    columns.where(position: start..stop).destroy_all
    columns.each_with_index do |column,i|
      column.position = i
      column.save
    end
  end

  # Remove pos[:count] rows at position pos[:at]
  def drop_row(pos)
    start = pos[:at].to_i
    count = pos[:count].to_i
    stop  = start + count - 1
    rows.where(position: start..stop).destroy_all
    rows.each_with_index do |row,i|
      row.position = i
      row.save
    end
  end

  # Update content of a Cell at the intersection of Row and Column
  def update_content(data)
    data.values.each do |change|
      row = change[0].to_i
      col = change[1].to_i
      cell = self[row][col]
      cell.content = change.last
      cell.save
    end
  end

  # Return Column headers, if set
  def column_headers
    use_column_headers ? columns.map(&:heading) : true
  end

  # Return Column headers, if set
  def row_headers
    use_row_headers ? rows.map(&:heading) : true
  end

  # Return a Row by position or an attribute by name
  def [](attr_name)
    if attr_name.class == Fixnum
      rows[attr_name]
    else
      read_attribute(attr_name) { |n| missing_attribute(n, caller) }
    end
  end

  private
  # Ensure the number of columns specified
  def create_columns
    (column_count.to_i - columns.size).times { columns.create(position: columns.size) }
  end

  # Ensure the number of rows specified
  def create_rows
    (row_count.to_i - rows.size).times { rows.create(position: rows.size) }
  end
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  before_action :set_sheet, only: [:show, :edit, :update, :destroy]

  def index
    @sheet = Sheet.new
    @sheets = Sheet.all
  end

  def show
  end

  def new
    redirect_to sheets_path
  end

  # POST /sheets
  def create
    sheet = params[:sheet][:sheet]
    params[:sheet].delete("sheet")

    if sheet
      if sheet.original_filename[/xls$/]
        if libreoffice_available?
          system "libreoffice --headless --convert-to xlsx #{sheet.tempfile.path} --outdir tmp"
          path = sheet.tempfile.path[1..-1] + ".xlsx"
        else
          flash[:error] = "Can't import MS Excel files without headless LibreOffice."
        end
      end
      if sheet.original_filename[/xlsx$/]
        path = sheet.tempfile.path
      end
      x = RubyXL::Parser.parse(path) if path
    end

    if x
      sheets = []
      x.sheets.each_with_index do |xsheet,xno|
        sheet = Sheet.new(name: xsheet.name, no_logging: true)
        sheets << sheet

        xrows = x[xno].sheet_data.rows

        sheet.row_count     = xrows.size
        sheet.column_count  = xrows.map(&:cells).map(&:size).sort.last
        sheet.save

        xrows.map(&:cells).each_with_index do |xrow,row|
          xrow.each_with_index do |cell,col|
            val = cell.value rescue nil
            unless val.blank?
              cell = sheet[row][col]
              cell.content = val
              cell.save
            end
          end
        end
      end
      redirect_to sheets_path, notice: "Sheets created: " + sheets.map(&:name).join(", ")
    else
      @sheet = Sheet.new(sheet_params)
      if @sheet.save
        redirect_to @sheet, notice: 'Sheet was successfully created.'
      else
        render :index
      end
    end
  end

  def edit
    binding.pry
  end

  # PUT /sheets/1
  # PUT /sheets/1.json
  def update
    @sheet.add_row(count_params) if params[:change] == "add_row"
    @sheet.add_column(count_params) if params[:change] == "add_column"
    @sheet.move_row(move_params) if params[:change] == "move_row"
    @sheet.move_column(move_params) if params[:change] == "move_column"
    @sheet.drop_row(count_params) if params[:change] == "drop_row"
    @sheet.drop_column(count_params) if params[:change] == "drop_column"

    @sheet.update_content(content_params) if params[:change] == "content"

    @sheet.update_attributes(sheet_params) if params[:sheet]

    respond_to do |format|
      if @sheet.save
        format.html { redirect_to @sheet, notice: 'Sheet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sheet
      @sheet = Sheet.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def sheet_params
      params.require(:sheet).permit(:name, :column_count, :row_count)
    end

    def libreoffice_available?
      system("which libreoffice > /dev/null") && !system("ps ax | grep -v grep | grep libreoffice > /dev/null")
    end

    def move_params
      params.permit(:from, :dest)
    end

    def count_params
      params.permit(:at, :count)
    end

    def content_params
      params.require(:data)
    end
end

app/helpers/sheets_helper.rb
module SheetsHelper
  def send_change(sheet, data)
    script=<<-eojs
$.ajax({
            url: "#{sheet_path(sheet)}",
            type: "put",
            dataType: "json",
            data: { #{data} }
          });
    eojs
    script.html_safe
  end
end

app/views/sheets/_sheet_form.html.erb
<%= form_for(@sheet) do |f| %>
  <% if @sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sheet.errors.count, "error") %> prohibited this sheet from being saved:</h2>

      <ul>
      <% @sheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h4>Create empty sheet</h4>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :columns %>
    <%= f.number_field :column_count %>
    <%= f.label :rows %>
    <%= f.number_field :row_count %>
  </div>

  <h4>or upload one</h4>
  <div class="field">
    <%= f.label :sheets_from_file %>
    <%= f.file_field :sheet %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sheets/index.html.erb
<h1>Sheets</h1>

<%= render partial: "sheets/sheet_form" %>

<ul>
<% @sheets.each do |sheet| %>
  <li><%= link_to sheet.name, sheet %></li>
<% end %>
</ul>

app/views/sheets/show.html.erb
<h1>
  <%= best_in_place @sheet, :name %>
</h1>

<%= label_tag "search" %>
<%= text_field_tag "search_field" %>

<div id="myModal" class="reveal-modal">
    <h1 id="modal_heading">Formel</h1>
    <%= form_for edit_sheet_column_path(sheet_id: @sheet.id, id: 9) do |f| %>
      <%= f.text_field :formula %>
    <% end %>

    <a class="close-reveal-modal">&#215;</a>
</div>

<div id="hot"></div>

<script>


  var data = <%= @sheet.data.html_safe %>,
  container = document.getElementById('hot'),
  autosaveNotification,
  hot = new Handsontable(container,
    {
      data: data,
      search: {
        searchResultClass: 'text-info'
      },
      minSpareRows: 1,
      manualRowMove: true,
      manualColMove: true,
      rowHeaders: <%= @sheet.row_headers %>,
      colHeaders: <%= @sheet.column_headers %>,
      contextMenu: true,
//      columns: <%# @sheet.columns.to_json.html_safe %>,
      afterChange: function (change, source) {
          if (source === 'loadData') {
            return; //don't save this change
          }
          <%= send_change(@sheet, "change: 'content', data: change") %>
      },
      afterCreateRow: function (position, count) {
        <%= send_change(@sheet, "change: 'add_row', at: position, count: count") %>
      },
      afterCreateCol: function (position, count) {
        <%= send_change(@sheet, "change: 'add_column', at: position, count: count") %>
      },
      afterColMove: function(position, destination) {
        <%= send_change(@sheet, "change: 'move_column', from: position, dest: destination") %>
      },
      afterRowMove: function(position, destination) {
        <%= send_change(@sheet, "change: 'move_row', from: position, dest: destination") %>
      },

      // Remove columns/rows
      beforeRemoveCol: function () { confirm("Do you really want to delete this column?"); },
      beforeRemoveRow: function () { confirm("Do you really want to delete this row?"); },
      afterRemoveCol: function (position, count) {
        <%= send_change(@sheet, "change: 'drop_column', at: position, count: count") %>
      },
      afterRemoveRow: function (position, count) {
        <%= send_change(@sheet, "change: 'drop_row', at: position, count: count") %>
      },

      afterOnCellMouseDown: function (event, coords, td) {
        if (coords.row == -1) {
          console.log(event, coords, td);
          col = coords.col;

          <%= get_column(@sheet.id, "col") %>

          $('#myModal').reveal({
               animation: 'fadeAndPop',                   //fade, fadeAndPop, none
               animationspeed: 300,                       //how fast animtions are
               closeonbackgroundclick: true,              //if you click background will modal close?
               dismissmodalclass: 'close-reveal-modal'    //the class of a button or element that will close an open modal
          });
        }
      }
    });

    var onlyExactMatch = function (queryStr, value) {
      return queryStr.toString() === value.toString();
    };

    var searchFiled = document.getElementById('search_field');
    Handsontable.Dom.addEvent(searchFiled,'keyup', function (event) {
        var queryResult = hot.search.query(this.value);
        console.log(queryResult);
        hot.render();
    });
    function updateForm(data) {
        $("#myModal").html(data);
        console.log(col);
      };
</script>